mail:
  mail_support:
    host: 172.31.7.44
    port: 587
    protocol: smtp
    user: no-reply@exrates.top
    password: 5zaL6GD2uJ
  mail_support_2:
    host: 172.31.1.96
    port: 587
    protocol: smtp
    user: no-reply@exrates.top
    password: 5zaL6GD2uJ
  send_grid:
    host: smtp.sendgrid.net
    port: 25
    protocol: smtp
    user: StasGorobzeev
    password: gkYY1k23YJRUxN4R
